"""Resamples a complex Sentinel1 burst."""

from __future__ import annotations

import numpy as np

from eos.products.sentinel1.metadata import Sentinel1BurstMetadata
from eos.sar import io, regist, roi

from . import doppler_info


def burst_resample_from_meta(
    burst_meta: Sentinel1BurstMetadata,
    dst_burst_shape: tuple[int, int],
    matrix,
    doppler: doppler_info.Sentinel1Doppler,
    **kwargs,
) -> Sentinel1BurstResample:
    """Create a Sentinel1BurstResample instance from a Sentinel1Model\
    instance and additional parameters.

    Parameters
    ----------
    burst_meta : Sentinel1BurstMetadata
        Metadata of the burst to be resampled.
    dst_burst_shape : tuple
        (h, w) shape of the destination burst.
    matrix : ndarray
        Affine registration matrix.
    doppler: eos.products.sentinel1.Sentinel1Doppler
        Object used to compute the Doppler info within a burst
    **kwargs: Keyword arguments of the constructor
        [dst_roi_in_burst, src_roi_in_burst]

    Returns
    -------
    Sentinel1BurstResample
        Instance that can be used to resample the complex burst array.
    """

    return Sentinel1BurstResample(
        burst_meta.burst_roi,
        dst_burst_shape,
        matrix,
        doppler,
        burst_meta.lines_per_burst,
        burst_meta.azimuth_frequency,
        burst_meta.range_frequency,
        burst_meta.slant_range_time,
        burst_meta.burst_times,
        **kwargs,
    )


class Sentinel1BurstResample(regist.SarResample):
    """Resample a complex Sentinel1 burst.

    For more info:
    Miranda, N. (2015). Definition of the TOPS SLC deramping function
    for products generated by the S-1 IPF. 1–15.
    """

    def to_dict(self) -> dict:
        """Serialize this resampler to a plain, JSON-friendly dict."""
        return dict(
            src_burst_roi=self.src_burst_roi.to_roi(),
            dst_burst_shape=self.dst_burst_shape,
            burst_matrix=self.burst_matrix.tolist(),
            doppler=self.doppler.to_dict(),
            lines_per_burst=self.lines_per_burst,
            azimuth_frequency=self.azimuth_frequency,
            range_frequency=self.range_frequency,
            slant_range_time=self.slant_range_time,
            burst_times=self.burst_times,
            dst_roi_in_burst=self.dst_roi_in_burst.to_roi(),
            src_roi_in_burst=self.src_roi_in_burst.to_roi(),
        )

    @staticmethod
    def from_dict(bresamp_dict):
        """Build a `Sentinel1BurstResample` from a dict produced by `to_dict`."""
        return Sentinel1BurstResample(
            src_burst_roi=bresamp_dict["src_burst_roi"],
            dst_burst_shape=bresamp_dict["dst_burst_shape"],
            burst_matrix=np.array(bresamp_dict["burst_matrix"]),
            doppler=doppler_info.Sentinel1Doppler.from_dict(bresamp_dict["doppler"]),
            lines_per_burst=bresamp_dict["lines_per_burst"],
            azimuth_frequency=bresamp_dict["azimuth_frequency"],
            range_frequency=bresamp_dict["range_frequency"],
            slant_range_time=bresamp_dict["slant_range_time"],
            burst_times=bresamp_dict["burst_times"],
            dst_roi_in_burst=roi.Roi.from_roi_tuple(bresamp_dict["dst_roi_in_burst"]),
            src_roi_in_burst=roi.Roi.from_roi_tuple(bresamp_dict["src_roi_in_burst"]),
        )

    def __init__(
        self,
        src_burst_roi,
        dst_burst_shape,
        burst_matrix,
        doppler: doppler_info.Sentinel1Doppler,
        lines_per_burst,
        azimuth_frequency,
        range_frequency,
        slant_range_time,
        burst_times,
        dst_roi_in_burst=None,
        src_roi_in_burst=None,
    ):
        """Instantiate a Sentinel1BurstResample object.

        Parameters
        ----------
        src_burst_roi : tuple
            (col, row, w, h) of the burst roi in the sentinel1 product
            of the burst to be resampled.
        dst_burst_shape : tuple
            (h, w) of the destination burst.
        burst_matrix : 3x3 ndarray
            Resampling matrix such as burst_matrix*dst_coord = src_coord of bursts
        doppler : Sentinel1Doppler
        lines_per_burst : int
            Lines per burst (with invalid data)
            as read from sentinel1 metadata.
        azimuth_frequency : float
            Azimuth sampling frequency.
        range_frequency : float
            Range sampling frequency.
        slant_range_time : float
            Two way range time of first (invalid) column in the burst.
        burst_times : tuple
            (start, start_valid, end_valid) azimuth times.
        dst_roi_in_burst : eos.sar.roi.Roi, optional.
            dst roi in dst burst coordinates. If None, the whole destination
            burst is considered. The default is None.
        src_roi_in_burst : eos.sar.roi.Roi, optional.
            src roi in src burst coordinates. If None, the whole source
            burst is considered. The default is None.

        Returns
        -------
        None.

        """
        # set the abstract variables
        # burst level quantities
        self.src_burst_roi = roi.Roi.from_roi_tuple(src_burst_roi)
        self.dst_burst_shape = dst_burst_shape
        self.burst_matrix = burst_matrix
        self.doppler = doppler

        # replicate some quantities
        # set resampling params
        if src_roi_in_burst is None:
            # whole source burst is considered
            h, w = self.src_burst_roi.get_shape()
            src_roi_in_burst = roi.Roi(0, 0, w, h)
        if dst_roi_in_burst is None:
            # whole destination frame will be considered
            h, w = dst_burst_shape
            dst_roi_in_burst = roi.Roi(0, 0, w, h)

        col_src, row_src = src_roi_in_burst.get_origin()
        col_dst, row_dst, w_dst, h_dst = dst_roi_in_burst.to_roi()

        # adapt the matrix
        self.matrix = regist.change_resamp_mat_orig(
            row_dst, col_dst, row_src, col_src, self.burst_matrix
        )
        # set self.src_roi_in_burst
        self.src_roi_in_burst = src_roi_in_burst

        # set self.dst_roi_in_burst
        self.dst_roi_in_burst = dst_roi_in_burst

        # change self.dst_shape
        self.dst_shape = (h_dst, w_dst)

        # set the product variables
        self.lines_per_burst = lines_per_burst

        self.azimuth_frequency = azimuth_frequency
        self.range_frequency = range_frequency

        self.slant_range_time = slant_range_time

        # set variables specific to burst
        self.burst_times = burst_times

    def get_resampler_on_different_roi(
        self, dst_roi_in_burst: roi.Roi, src_roi_in_burst: roi.Roi
    ):
        """
        Create a new instance (copy), but on different roi.

        Parameters
        ----------
        dst_roi_in_burst : roi.Roi
            dst roi in dst burst coordinates.
        src_roi_in_burst : roi.Roi
            src roi in src burst coordinates.

        Returns
        -------
        Sentinel1BurstResample
            A new instance of Sentinel1BurstResample set on the new rois.

        """
        # create a new instance with similar stuff, but on different roi
        return Sentinel1BurstResample(
            self.src_burst_roi.to_roi(),
            self.dst_burst_shape,
            self.burst_matrix,
            self.doppler,
            self.lines_per_burst,
            self.azimuth_frequency,
            self.range_frequency,
            self.slant_range_time,
            self.burst_times,
            dst_roi_in_burst,
            src_roi_in_burst,
        )

    def src_roi_from_dst_roi(self, dst_roi_in_burst, margin=5):
        """
        Get the source roi in burst from the destination roi in burst.

        Parameters
        ----------
        dst_roi_in_burst : eos.sar.roi.Roi
            dst roi in dst burst coordinates.
        margin : int, optional
            Pixel safety margin to be applied after warping the destination roi.
            The default is 5.

        Returns
        -------
        src_roi_in_burst: eos.sar.roi.Roi.
            src roi in src burst coordinates

        """
        src_roi_in_burst = dst_roi_in_burst.warp_valid_roi(
            self.dst_burst_shape,
            self.src_burst_roi.get_shape(),
            self.burst_matrix,
            margin=margin,
        )
        return src_roi_in_burst

    def to_eta_slrt(self, row, col):
        """Convert row, col to eta, slrt.

        Parameters
        ----------
        row : ndarray
            Row with respect to first valid line in the burst.
        col : ndarray
            Col with respect to the first valid column in the burst.

        Returns
        -------
        eta : ndarray
            Azimuth time w.r.t. the central line in the burst.
            The central line takes into account invalid lines.
        slrt : ndarray
            Range dependent doppler rate, i.e. the classical
            (stripmap) azimuth fm rate.
            We call it range dependent because it is computed as a polynomial
            w.r.t. range. A doppler rate denotes the rate at which
            the azimuth frequency is shifted along the aquisition.

        """
        eta = (self.burst_times[1] - self.burst_times[0]) + (
            row - (self.lines_per_burst - 1) / 2
        ) / self.azimuth_frequency
        slrt = (
            self.src_burst_roi.col + col
        ) / self.range_frequency + self.slant_range_time
        return eta, slrt

    def get_doppler_params(
        self,
        rows_roi,
        cols_roi,
        roi_origin_in_doppler_frame,
        matrix_to_doppler_frame_roi=None,
    ):
        """
        Get the Doppler parameters for a set of rows, cols locations within a roi.
        The roi in this function is with respect to the burst.
        Also supports computation on a roi that has already been resampled if the
        matrix is provided.

        Parameters
        ----------
        rows_roi : np.1darray (nrows, )
            Rows within the roi on which to compute the Doppler parameters.
        cols_roi : np.1darray (ncols, )
            Cols within the roi on which to compute the Doppler parameters.
        roi_origin_in_doppler_frame : tuple
            (col, row) in the original BURST frame provided by ESA, on which the provided
            ESA polynomials for the Doppler parameters can be applied.
        matrix_to_doppler_frame_roi : np.2darray, optional
            Backward matrix between the resampled roi and the original src roi.
            If provided, input coordinates are assumed to be for a set of points and
            the condition nrows == ncols is checked. Otherwise, it is possible to compute
            the parameters even if nrows != ncols. The default is None.

        Returns
        -------
        eta : np.ndarray, (nrows, )
            Azimuth time referenced to burst mid time.
        ref_time : np.ndarray, (ncols, )
            Azimuth doppler reference time.
        dop_centroid : np.ndarray, (ncols, )
            Doppler centroid.
        dop_rate : np.ndarray, (ncols, )
            Doppler rate.
        """
        # reference row_src and col_src w.r.t. the burst origin
        col_roi, row_roi = roi_origin_in_doppler_frame

        rows_roi_in_dop_frame = rows_roi
        cols_roi_in_dop_frame = cols_roi

        if matrix_to_doppler_frame_roi is not None:
            # in this case, ensure that given arrays are of the same length (points)
            assert len(rows_roi) == len(cols_roi), (
                "Cols and Rows arrays must be of same length."
            )
            # homogeneous coordinates
            dst_points = np.vstack(
                [
                    rows_roi_in_dop_frame,
                    cols_roi_in_dop_frame,
                    np.ones_like(rows_roi_in_dop_frame),
                ]
            )
            # grid at src
            (
                rows_roi_in_dop_frame,
                cols_roi_in_dop_frame,
            ) = matrix_to_doppler_frame_roi.dot(dst_points)[:2]
            del dst_points

        eta, slrt = self.to_eta_slrt(
            rows_roi_in_dop_frame + row_roi, cols_roi_in_dop_frame + col_roi
        )
        del rows_roi_in_dop_frame
        del cols_roi_in_dop_frame

        # all Doppler quantities
        rg_dpt_dop_rate = self.doppler.get_rg_dpt_dop_rate(slrt)
        dop_centroid = self.doppler.get_dop_centroid(slrt)
        del slrt
        ref_time = self.doppler.get_ref_time(dop_centroid, rg_dpt_dop_rate)
        dop_rate = self.doppler.get_dop_rate(rg_dpt_dop_rate)
        del rg_dpt_dop_rate

        return eta, ref_time, dop_centroid, dop_rate

    def get_doppler_params_gridded(
        self,
        rows_roi,
        cols_roi,
        roi_origin_in_doppler_frame,
        matrix_to_doppler_frame_roi=None,
    ):
        """
        Get the Doppler parameters for a set of locations within a roi (reference to a burst)
        defined by the meshgrid of the given rows_roi, cols_roi.
        Also supports computation on a roi that has already been resampled if the
        matrix is provided.

        Parameters
        ----------
        rows_roi : np.1darray (nrows, )
            Rows within the roi on which to compute the Doppler parameters.
        cols_roi : np.1darray (ncols, )
            Cols within the roi on which to compute the Doppler parameters.
        roi_origin_in_doppler_frame : tuple
            (col, row) in the original BURST frame provided by ESA, on which the provided
            ESA polynomials for the Doppler parameters can be applied.
        matrix_to_doppler_frame_roi : np.2darray, optional
            Backward matrix between the resampled roi and the original src roi.
            The default is None.

        Returns
        -------
        eta : np.ndarray, (nrows, ncols)
            Azimuth time referenced to burst mid time.
        ref_time : np.ndarray, (nrows, ncols)
            Azimuth doppler reference time.
        dop_centroid : np.ndarray, (nrows, ncols)
            Doppler centroid.
        dop_rate : np.ndarray, (nrows, ncols)
            Doppler rate.
        """
        cols_roi_mesh, rows_roi_mesh = np.meshgrid(cols_roi, rows_roi)
        rows_roi_pts = rows_roi_mesh.ravel()
        cols_roi_pts = cols_roi_mesh.ravel()
        del rows_roi_mesh
        del cols_roi_mesh

        eta, ref_time, dop_centroid, dop_rate = self.get_doppler_params(
            rows_roi_pts,
            cols_roi_pts,
            roi_origin_in_doppler_frame,
            matrix_to_doppler_frame_roi,
        )

        out_shape = (len(rows_roi), (len(cols_roi)))

        eta = eta.reshape(out_shape)
        ref_time = ref_time.reshape(out_shape)
        dop_centroid = dop_centroid.reshape(out_shape)
        dop_rate = dop_rate.reshape(out_shape)

        return eta, ref_time, dop_centroid, dop_rate

    def get_phi_ramp(
        self,
        rows_roi,
        cols_roi,
        roi_origin_in_doppler_frame,
        matrix_to_doppler_frame_roi=None,
    ):
        """
        Get the phase ramp present in the data at certain locations within a
        roi (reference to a burst) defined by the points (rows_roi, cols_roi).

        Parameters
        ----------
        rows_roi : np.1darray (npts, )
            Row coordinates of the points within the roi on which to compute the phase ramp.
        cols_roi : np.1darray (npts, )
            Col coordinates of the points within the roi on which to compute the phase ramp.
        roi_origin_in_doppler_frame : tuple
            (col, row) in the original BURST frame provided by ESA, on which the provided
            ESA polynomials for the Doppler parameters can be applied.
        matrix_to_doppler_frame_roi : np.2darray, optional
            Backward matrix between the resampled roi and the original src roi. The default is None.

        Returns
        -------
        phi : np.ndarray, (npts, ).
            Phase ramp, i.e. the parabola present in the data because of the TOPSAR mode.
        """
        assert len(rows_roi) == len(cols_roi), (
            "Cols and Rows arrays must be of same length."
        )
        eta, ref_time, dop_centroid, dop_rate = self.get_doppler_params(
            rows_roi, cols_roi, roi_origin_in_doppler_frame, matrix_to_doppler_frame_roi
        )

        deta = eta - ref_time

        phi = (np.pi * dop_rate * deta + 2 * np.pi * dop_centroid) * deta

        return phi

    def get_phi_ramp_gridded(
        self,
        rows_roi,
        cols_roi,
        roi_origin_in_doppler_frame,
        matrix_to_doppler_frame_roi=None,
    ):
        """
        Get the phase ramp present in the data at certain locations within a
        roi (reference to a burst) defined by the meshgrid of the given rows_roi, cols_roi.

        Parameters
        ----------
        rows_roi : np.1darray (nrows, )
            Rows within the roi on which to compute the phase ramp.
        cols_roi : np.1darray (ncols, )
            Cols within the roi on which to compute the phase ramp.
        roi_origin_in_doppler_frame : tuple
            (col, row) in the original BURST frame provided by ESA, on which the provided
            ESA polynomials for the Doppler parameters can be applied.
        matrix_to_doppler_frame_roi : np.2darray, optional
            Backward matrix between the resampled roi and the original src roi. The default is None.

        Returns
        -------
        phi : np.ndarray, (nrows, ncols).
            Phase ramp, i.e. the parabola present in the data because of the TOPSAR mode.
        """
        if matrix_to_doppler_frame_roi is None:
            # already in the doppler frame
            eta, ref_time, dop_centroid, dop_rate = self.get_doppler_params(
                rows_roi, cols_roi, roi_origin_in_doppler_frame
            )
            # reshape the 1D vectors for broadcasting
            dop_centroid = dop_centroid[None, :]
            ref_time = ref_time[None, :]
            dop_rate = dop_rate[None, :]
            eta = eta[:, None]
        else:
            eta, ref_time, dop_centroid, dop_rate = self.get_doppler_params_gridded(
                rows_roi,
                cols_roi,
                roi_origin_in_doppler_frame,
                matrix_to_doppler_frame_roi,
            )

        deta = eta - ref_time

        phi = (np.pi * dop_rate * deta + 2 * np.pi * dop_centroid) * deta

        return phi

    def deramp(self, src_array):
        """Deramp on the regular grid of the src array.

        Parameters
        ----------
        src_array : ndarray
            Burst array to be deramped.

        Returns
        -------
        ndarray
            Deramped burst.
            The fourrier spectrum now has no aliasing in azimuth and is
            centered around the zero frequency. Resampling can be safely
            done after this step.

        """
        assert src_array.shape == self.src_roi_in_burst.get_shape(), (
            "src array is not of the expected shape"
        )

        col0, row0, w, h = self.src_roi_in_burst.to_roi()

        phi = -self.get_phi_ramp_gridded(np.arange(h), np.arange(w), (col0, row0))

        deramping_func = np.exp(1j * phi, dtype=np.complex64)

        return src_array * deramping_func

    def reramp(self, dst_array):
        """Reramp on the regular grid of the destination array\
        after resampling. Therefore, this corresponds to an irregular grid in\
        the source array. The deramping phase is estimated at each pixel of\
        the irregular grid and compensated.

        Parameters
        ----------
        dst_array : ndarray
            Resampled burst.

        Returns
        -------
        ndarray
            Reramped burst.

        """
        assert dst_array.shape == self.dst_shape, (
            "destination array is not of the expected shape"
        )

        phi = self.get_phi_ramp_gridded(
            np.arange(self.dst_shape[0]),
            np.arange(self.dst_shape[1]),
            self.src_roi_in_burst.get_origin(),
            matrix_to_doppler_frame_roi=self.matrix,
        )

        reramping_func = np.exp(1j * phi, dtype=np.complex64)

        return dst_array * reramping_func.reshape(self.dst_shape)


class ResampledBurstResampler(regist.SarResample):
    """Class to Resample a roi again within a resampled roi."""

    def __init__(
        self,
        src_roi_within_dst_roi,
        backward_matrix,
        dst_shape,
        previous_burst_resampler,
    ):
        """
        Constructor.

        Parameters
        ----------
        src_roi_within_dst_roi : eos.sar.roi.Roi
            Roi to resample again referenced to the roi produced by the first resampling.
        backward_matrix : np.ndarray
            Backward resampling matrix to apply to the roi.
        dst_shape : tuple
            (h, w) of the resampled output array. Should be set for regist.SarResample base Class.
        previous_burst_resampler : Sentinel1BurstResample
            Resampler used in the first (previous) resampling.

        Returns
        -------
        None.

        """
        # set matrix and dst_shape
        self.src_roi_within_dst_roi = src_roi_within_dst_roi
        self.dst_shape = dst_shape
        self.matrix = backward_matrix
        self.previous_burst_resampler = previous_burst_resampler

    def deramp(self, src_array):
        """
        Deramp the src array corresponding to src_roi_within_dst_roi, i.e.
        the array after the first resampling.

        Parameters
        ----------
        src_array : np.ndarray
            Array to be deramped.

        Returns
        -------
        np.ndarray
            Deramped array.

        """
        col, row, w, h = self.src_roi_within_dst_roi.to_roi()

        assert src_array.shape == (h, w), "source array is not of the expected shape"

        phi = -self.previous_burst_resampler.get_phi_ramp_gridded(
            np.arange(row, row + h),
            np.arange(col, col + w),
            self.previous_burst_resampler.src_roi_in_burst.get_origin(),
            matrix_to_doppler_frame_roi=self.previous_burst_resampler.matrix,
        )

        deramping_func = np.exp(1j * phi, dtype=np.complex64)

        return src_array * deramping_func

    def reramp(self, dst_array):
        """
        Reramp resampled array (after the second resampling)

        Parameters
        ----------
        dst_array : np.ndarray
            Array to be reramped.

        Returns
        -------
        np.ndarray
            Reramped array.

        """
        assert dst_array.shape == self.dst_shape, (
            "destination array is not of the expected shape"
        )

        # All of the work is in the matrix to doppler params
        # self.matrix takes from dst to src
        # a translation must be added to go the dst roi of the previous resampler
        # then previous resampler matrix should be enough
        matrix_to_doppler_frame_roi = self.previous_burst_resampler.matrix.dot(
            regist.translation_matrix(*self.src_roi_within_dst_roi.get_origin())
        ).dot(self.matrix)

        phi = self.previous_burst_resampler.get_phi_ramp_gridded(
            np.arange(self.dst_shape[0]),
            np.arange(self.dst_shape[1]),
            self.previous_burst_resampler.src_roi_in_burst.get_origin(),
            matrix_to_doppler_frame_roi=matrix_to_doppler_frame_roi,
        )

        reramping_func = np.exp(1j * phi, dtype=np.complex64)

        return dst_array * reramping_func.reshape(self.dst_shape)


def get_read_roi_src_and_resampler(
    resampler: Sentinel1BurstResample,
    dst_roi_in_burst: roi.Roi,
    burst_orig_src_in_tiff: tuple[int, int],
    margin: int = 5,
) -> tuple[roi.Roi, Sentinel1BurstResample]:
    """
    Use the resampler already set on the burst (containing burst resampling matrix)
    to get the roi in the source burst. Use burst_orig to get where we need to read.\
    Update the resampler on the roi. src and dst refer to source and destination,\
        because the function is called in a context where a source region needs
        to be resampled onto a destination region.

    Parameters
    ----------
    resampler: Sentinel1BurstResample
        Resampler set on the burst under study.
    dst_roi_in_burst : eos.sar.roi.Roi
        roi of the destination region w.r.t. the burst coordinate system.
    burst_orig_src_in_tiff : tuple
        (col, row) the location of the burst orig in the tiff for the source grid.
    margin : int, optional
        Pixel safety margin to be applied after warping the destination region. The default is 5.

    Returns
    -------
    read_roi_src : eos.sar.roi.Roi
        Roi containing coordinates of the region under study in the tiff of the source grid. It
        is obtained after warping dst_roi_in_burst and adding a safety margin, and shifting the origin.
    resampler_on_roi : Sentinel1BurstResample
        Resampler that can be directly applied on the array read using read_roi_src.

    """
    # warp the roi
    src_roi_in_burst = resampler.src_roi_from_dst_roi(dst_roi_in_burst, margin)

    col_src, row_src = burst_orig_src_in_tiff
    # read_roi in src burst, adding the origin
    read_roi_src = src_roi_in_burst.translate_roi(col_src, row_src)

    # get the new resampler
    resampler_on_roi = resampler.get_resampler_on_different_roi(
        dst_roi_in_burst, src_roi_in_burst
    )
    return read_roi_src, resampler_on_roi


def warp_roi_read_resample(
    resampler,
    dst_roi_in_burst,
    burst_orig_src_in_tiff,
    image_reader,
    get_complex=True,
    margin=5,
    reramp=True,
):
    """
    Warp the roi to the source frame, read, then resample to the destination frame.

    Parameters
    ----------
    resampler: Sentinel1BurstResample
        Resampler set on the burst under study.
    dst_roi_in_burst : eos.sar.roi.Roi
        roi of the destination region w.r.t. the burst coordinate system.
    burst_orig_src_in_tiff : tuple
        (col, row) the location of the burst orig in the tiff for the source grid.
    image_reader : opened rasterio dataset or any object supporting windowed reading \
        `image_reader.read(1, window=((row, row+h), (col, col+w)))`
        Reader on the source tiff.
    get_complex : boolean, optional
        If True, the complex array is read and resampled. The default is True.
    margin : int, optional
        Pixel safety margin to be applied after warping the destination region. The default is 5.
    reramp : bool
        Set to False to avoid reramping after resampling.

    Returns
    -------
    burst_array_resamp : ndarray
        Resampled source array onto the destination region.
    read_roi_src : eos.sar.roi.Roi
        Roi containing coordinates of the region under study in the tiff of the source grid. It
        is obtained after warping read_roi_dst and adding a safety margin.
    resampler_on_roi : Sentinel1BurstResample
        Resampler that was applied on the array read using read_roi_src.
    """
    read_roi_src, resampler_on_roi = get_read_roi_src_and_resampler(
        resampler, dst_roi_in_burst, burst_orig_src_in_tiff, margin
    )

    padded_burst_array = io.read_window(image_reader, read_roi_src, get_complex)

    burst_array_resamp = resampler_on_roi.resample(padded_burst_array, reramp=reramp)

    return burst_array_resamp, read_roi_src, resampler_on_roi
